onboarding = false

[worktrees]
directory = "~/.herdr/worktrees"

[keys]
split_vertical   = ["prefix+|"]
split_horizontal = ["prefix+-"]
focus_pane_left  = ["alt+left"]
focus_pane_down  = ["alt+down"]
focus_pane_up    = ["alt+up"]
focus_pane_right = ["alt+right"]
