alias gst='git status'
alias gc='git commit'
alias gco='git checkout'
alias gpull='git pull'
alias gpom="git pull origin master"
alias gpush='git push'
alias gd='git diff'
alias gb='git branch -a'
alias gdel='git branch -d'
